---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 80}]
    - ["private_network", {ip: "192.168.10.101"}]
provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: sbeliakou/centos-7.3-x86_64-minimal

suites:
  - name: default
    run_list:
      - recipe[my_custom_cb::default]
      - recipe[my_custom_cb::deploy]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      java:
        install_flavor: 'openjdk'
        jdk_version: '8'
